include $(APPDIR)/Make.defs

# Magnetometer Calibration built-in application info

PROGNAME  = $(CONFIG_INSPACE_MAG_CALIBRATION_PROGNAME)
PRIORITY  = $(CONFIG_INSPACE_MAG_CALIBRATION_PRIORITY)
STACKSIZE = $(CONFIG_INSPACE_MAG_CALIBRATION_STACKSIZE)
MODULE    = $(CONFIG_INSPACE_MAG_CALIBRATION)

# Magnetometer Calibration application

MAINSRC = mag_calibration_main.c

include $(APPDIR)/Application.mk
